package Exception_Handling;

public class demo 
{
	public static void main(String[] args) 
	{
		try
		{
			
		} 
		catch(ArithmeticException e)
		{
			exit;
		}
		finally 
		{
			System.out.println("finally");
		}
		
	}

}
